export const FETCH_LOCATION_REQUEST = 'FETCH_LOCATION_REQUEST';
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';
export const SET_REGION = 'SET_REGION';
export const SET_PICKUP = 'SET_PICKUP';

export const FETCH_DESTINATION_REQUEST = 'FETCH_DESTINATION_REQUEST';
export const FETCH_DESTINATION_SUCCESS = 'FETCH_DESTINATION_SUCCESS';
export const FETCH_DESTINATION_ERROR = 'FETCH_DESTINATION_ERROR';
export const CHOOSE_DESTINATION_ON_MAP = 'CHOOSE_DESTINATION_ON_MAP';
export const FETCH_DIRECTIONS_REQUEST = 'FETCH_DIRECTIONS_REQUEST';
export const FETCH_DIRECTIONS_SUCCESS = 'FETCH_DIRECTIONS_SUCCESS';
export const FETCH_DIRECTIONS_ERROR = 'FETCH_DIRECTIONS_ERROR';

export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_ERROR = 'FETCH_CARS_ERROR';
