export const FETCH_LOCATION_REQUEST = 'FETCH_LOCATION_REQUEST';
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';
export const SET_REGION = 'SET_REGION';

export const SET_ADDRESS = 'SET_ADDRESS';
export const FETCH_COORDINATES_REQUEST = 'FETCH_COORDINATES_REQUEST';
export const FETCH_COORDINATES_SUCCESS = 'FETCH_COORDINATES_SUCCESS';
export const FETCH_COORDINATES_ERROR = 'FETCH_COORDINATES_ERROR';
export const FETCH_DIRECTIONS_REQUEST = 'FETCH_DIRECTIONS_REQUEST';
export const FETCH_DIRECTIONS_SUCCESS = 'FETCH_DIRECTIONS_SUCCESS';
export const FETCH_DIRECTIONS_ERROR = 'FETCH_DIRECTIONS_ERROR';
